apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: testcpu-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: synergychat-testcpu-6955d59d85-8727z
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 50